[y1, fs] = audioread("crazy_eyes.wav");
[y2, fs] = audioread("wroclaw.wav");
N = 1000;
x = (0:N-1) / fs;
b = [0.1, 0.2, 0.3];
y1_filtered = fir_filter(y1, b);
y2_filtered = fir_filter(y2, b);
y = conv(y1_filtered, y2_filtered);
player = audioplayer(y, fs);
playblocking(player);
audiowrite("splot.wav", y, fs);
figure(1);
subplot(3,1,1);
plot(x, y1(1:N));
title('Sygnał pierwszy');
xlabel('Czas [s]');
ylabel('Amplituda');
subplot(3,1,2);
plot(x, y2(1:N));
title('Sygnał drugi');
xlabel('Czas [s]');
ylabel('Amplituda');
subplot(3,1,3);
plot(x, y(1:N));
title('Wynik filtracji');
xlabel('Czas [s]');
ylabel('Amplituda');
